# Generated by Django 5.2.4 on 2025-08-05 10:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_postimage_image_alter_postvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='video'),
            preserve_default=False,
        ),
    ]
